FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    cmake \
    pkg-config \
    libeigen3-dev \
    libpng-dev \
    libboost-all-dev \
    build-essential
